import React from 'react';

import * as Constants from '../resources/constants';

export default class Table extends React.Component {
  render() {
    return (
      <div>
        <h2>Tabela</h2>
        <table>
          <tr>
            <th>Time</th>
            <th>P</th>
            <th>J</th>
            <th>V</th>
            <th>E</th>
            <th>D</th>
            <th>GP</th>
            <th>GC</th>
            <th>SG</th>
            <th>%</th>
          </tr>
          <tr>
            <td>{Constants.ALVORADA}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.ATLETICO}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.CAMAROES}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.CARIRI}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.GONZAGAO}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.INTERNACIONAL}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.MACEDAO}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.PALMEIRAS}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.SAMPAIAO}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.SAO_PAULO}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.SPORT}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
          <tr>
            <td>{Constants.VILA_UNIAO}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0%</td>
          </tr>
        </table>
      </div>
    );
  }
}